// Generated by Bisonc++ V6.01.00 on Tue, 12 Nov 2019 12:26:20 +0300

// hdr/includes
#ifndef ParserBase_h_included
#define ParserBase_h_included

#include <exception>
#include <vector>
#include <iostream>
// $insert polyincludes
#include <memory>
// $insert preincludes
#include "ParserPreinclude.h"
// $insert debugincludes
#include <iostream>
#include <sstream>
#include <string>
#include <iomanip>
#include <unordered_map>

// hdr/baseclass

namespace // anonymous
{
    struct PI__;
}


// $insert polymorphic
enum class Tag__
{
    SWITCH,
    IF,
    BLOCK,
    MATCH,
    STMT,
    EXPLIST,
    EXP,
    TOK,
    PARAMETERS,
    SIGNATURE,
    IDENT,
    IDENTIFY,
    NAME,
};

namespace Meta__
{

extern size_t const *t_nErrors;

extern size_t const *s_nErrors__;

template <Tag__ tag>
struct TypeOf;

template <typename Tp_>
struct TagOf;

// $insert polymorphicSpecializations
enum { sizeofTag__ = 13 };

extern char const *idOfTag__[];
template <>
struct TagOf<std::shared_ptr<Switch>>
{
    static Tag__ const tag = Tag__::SWITCH;
};

template <>
struct TagOf<std::shared_ptr<If>>
{
    static Tag__ const tag = Tag__::IF;
};

template <>
struct TagOf<std::shared_ptr<Block>>
{
    static Tag__ const tag = Tag__::BLOCK;
};

template <>
struct TagOf<std::shared_ptr<Match>>
{
    static Tag__ const tag = Tag__::MATCH;
};

template <>
struct TagOf<std::shared_ptr<Statement>>
{
    static Tag__ const tag = Tag__::STMT;
};

template <>
struct TagOf<std::shared_ptr<ExprList>>
{
    static Tag__ const tag = Tag__::EXPLIST;
};

template <>
struct TagOf<std::shared_ptr<Expression>>
{
    static Tag__ const tag = Tag__::EXP;
};

template <>
struct TagOf<Token>
{
    static Tag__ const tag = Tag__::TOK;
};

template <>
struct TagOf<std::shared_ptr<Parameters>>
{
    static Tag__ const tag = Tag__::PARAMETERS;
};

template <>
struct TagOf<std::shared_ptr<Signature>>
{
    static Tag__ const tag = Tag__::SIGNATURE;
};

template <>
struct TagOf<std::shared_ptr<Identifier>>
{
    static Tag__ const tag = Tag__::IDENT;
};

template <>
struct TagOf<std::shared_ptr<Identify>>
{
    static Tag__ const tag = Tag__::IDENTIFY;
};

template <>
struct TagOf<std::shared_ptr<Name>>
{
    static Tag__ const tag = Tag__::NAME;
};

template <>
struct TypeOf<Tag__::SWITCH>
{
    typedef std::shared_ptr<Switch> type;
};

template <>
struct TypeOf<Tag__::IF>
{
    typedef std::shared_ptr<If> type;
};

template <>
struct TypeOf<Tag__::BLOCK>
{
    typedef std::shared_ptr<Block> type;
};

template <>
struct TypeOf<Tag__::MATCH>
{
    typedef std::shared_ptr<Match> type;
};

template <>
struct TypeOf<Tag__::STMT>
{
    typedef std::shared_ptr<Statement> type;
};

template <>
struct TypeOf<Tag__::EXPLIST>
{
    typedef std::shared_ptr<ExprList> type;
};

template <>
struct TypeOf<Tag__::EXP>
{
    typedef std::shared_ptr<Expression> type;
};

template <>
struct TypeOf<Tag__::TOK>
{
    typedef Token type;
};

template <>
struct TypeOf<Tag__::PARAMETERS>
{
    typedef std::shared_ptr<Parameters> type;
};

template <>
struct TypeOf<Tag__::SIGNATURE>
{
    typedef std::shared_ptr<Signature> type;
};

template <>
struct TypeOf<Tag__::IDENT>
{
    typedef std::shared_ptr<Identifier> type;
};

template <>
struct TypeOf<Tag__::IDENTIFY>
{
    typedef std::shared_ptr<Identify> type;
};

template <>
struct TypeOf<Tag__::NAME>
{
    typedef std::shared_ptr<Name> type;
};


    // Individual semantic value classes are derived from Base, offering a
    // member returning the value's Tag__, a member cloning the object of its
    // derived Semantic<Tag__> and a member returning a pointerr to its
    // derived Semantic<Tag__> data. See also Bisonc++'s distribution file
    // README.polymorphic-techical
class Base
{
    protected:
        Tag__ d_baseTag;        // d_baseTag is assigned by Semantic.

    public:
        Base() = default;
        Base(Base const &other) = delete;

        virtual ~Base();

        Tag__ tag() const;
        Base *clone() const;
        void *data() const;        

    private:
        virtual Base *vClone() const = 0;
        virtual void *vData() const = 0;
};

inline Base *Base::clone() const
{
    return vClone();
}

inline void *Base::data() const
{
    return vData();
}

inline Tag__ Base::tag() const
{
    return d_baseTag;
}

    // The class Semantic stores a semantic value of the type matching tg_
template <Tag__ tg_>
class Semantic: public Base
{
    typename TypeOf<tg_>::type d_data;
    
    public:
        Semantic();
        Semantic(Semantic<tg_> const &other);   // req'd for cloning

            // This constructor member template forwards its arguments to
            // d_data, allowing it to be initialized using whatever
            // constructor is available for DataType
        template <typename ...Params>
        Semantic(Params &&...params);

    private:
        Base *vClone() const override;
        void *vData() const override;
};

template <Tag__ tg_>
Semantic<tg_>::Semantic()
{
    d_baseTag = tg_;                // Base's data member:
}

template <Tag__ tg_>
Semantic<tg_>::Semantic(Semantic<tg_> const &other)
:
    d_data(other.d_data)
{
    d_baseTag = other.d_baseTag;
}

template <Tag__ tg_>
template <typename ...Params>
Semantic<tg_>::Semantic(Params &&...params)
:
    d_data(std::forward<Params>(params) ...)
{
    d_baseTag = tg_;
}


template <Tag__ tg_>
Base *Semantic<tg_>::vClone() const
{
    return new Semantic<tg_>{*this};
}

template <Tag__ tg_>
void *Semantic<tg_>::vData() const 
{
    return const_cast<typename TypeOf<tg_>::type *>(&d_data);
}


    // The class SType wraps a pointer to Base.  It becomes the polymorphic
    // STYPE__ type. It also defines get members, allowing constructions like
    // $$.get<INT> to be used.  
class SType: private std::unique_ptr<Base>
{
    typedef std::unique_ptr<Base> BasePtr;

    public:
        SType() = default;
        SType(SType const &other);
        SType(SType &&tmp);

        ~SType() = default;

            // Specific overloads are needed for SType = SType assignments
        SType &operator=(SType const &rhs);
        SType &operator=(SType &rhs);           // required so it is used
                                                // instead of the template op=
        SType &operator=(SType &&tmp);

            // A template member operator= can be used when the compiler is
            // able to deduce the appropriate typename. Otherwise use assign.
        template <typename Type>
        SType &operator=(Type const &value);

        template <typename Type>                // same, now moving
        SType &operator=(Type &&tmp);

        template <Tag__ tag, typename ...Args>
        void assign(Args &&...args);
    
            // By default the get()-members check whether the specified <tag>
            // matches the tag returned by SType::tag (d_data's tag). If they
            // don't match a run-time fatal error results.
        template <Tag__ tag>
        typename TypeOf<tag>::type &get();

        template <Tag__ tag>
        typename TypeOf<tag>::type const &get() const;

        Tag__ tag() const;
        bool valid() const;
};

inline SType::SType(SType const &other)
:
    BasePtr{other ? other->clone() : 0}
{}

inline SType::SType(SType &&tmp)
:
    BasePtr{std::move(tmp)}
{}

inline SType &SType::operator=(SType const &rhs)
{
    reset(rhs->clone());
    return *this;
}

inline SType &SType::operator=(SType &rhs)
{
    reset(rhs->clone());
    return *this;
}

inline SType &SType::operator=(SType &&tmp)
{
    BasePtr::operator=(std::move(tmp));
    return *this;
}

    // A template assignment function can be used when the compiler is 
    // able to deduce the appropriate typename
template <typename Type>
inline SType &SType::operator=(Type const &value)
{
    assign< TagOf<Type>::tag >(value);
    return *this;
}

template <typename Type>
inline SType &SType::operator=(Type &&tmp)
{
    assign< 
        TagOf<
            typename std::remove_reference<Type>::type
        >::tag 
    >(std::move(tmp));

    return *this;
}

template <Tag__ tag, typename ...Args>
void SType::assign(Args &&...args)
{
    reset(new Semantic<tag>(std::forward<Args>(args) ...));
}

template <Tag__ tg>
typename TypeOf<tg>::type &SType::get()
{
// $insert warnTagMismatches

    if (tag() != tg)
    {
        if (*t_nErrors != 0)
            const_cast<SType *>(this)->assign<tg>();
        else
        {
            std::cerr << "[Fatal] calling `.get<Tag__::" << 
                idOfTag__[static_cast<int>(tg)] << 
                ">()', but Tag " <<
                idOfTag__[static_cast<int>(tag())] << " is encountered. Try "
                "option --debug and call setDebug(Parser::ACTIONCASES)\n";
            throw 1;        // ABORTs
        }
    }

    return *static_cast<typename TypeOf<tg>::type *>( (*this)->data() );
}

template <Tag__ tg>
typename TypeOf<tg>::type const &SType::get() const
{
// $insert warnTagMismatches

    if (tag() != tg)
    {
        if (*t_nErrors != 0)
            const_cast<SType *>(this)->assign<tg>();
        else
        {
            std::cerr << "[Fatal] calling `.get<Tag__::" << 
                idOfTag__[static_cast<int>(tg)] << 
                ">()', but Tag " <<
                idOfTag__[static_cast<int>(tag())] << " is encountered. Try "
                "option --debug and call setDebug(Parser::ACTIONCASES)\n";
            throw 1;        // ABORTs
        }
    }

    return *static_cast<typename TypeOf<tg>::type *>( (*this)->data() );
}

inline Tag__ SType::tag() const
{
    return valid() ? (*this)->tag() : static_cast<Tag__>(sizeofTag__);
}

inline bool SType::valid() const
{
    return BasePtr::get() != 0;
}

}  // namespace Meta__

class ParserBase
{
    public:
        enum DebugMode__
        {
            OFF           = 0,
            ON            = 1 << 0,
            ACTIONCASES   = 1 << 1
        };

// $insert tokens

    // Symbolic tokens:
    enum Tokens__
    {
        IDENTIFIER = 278,
        BOOLEAN,
        NUMBER,
        CHAR,
        STRING,
        EOL,
        INDENT,
        DEDENT,
        ERR_INDENT,
        ERR_CHAR,
        ERR_STRING,
        UNKNOWN_CHAR,
        CLASS,
        CONCEPT,
        DEF,
        RETURN,
        BREAK,
        CONTINUE,
        PASS,
        FOREVER,
        WHILE,
        FOR,
        IN,
        IF,
        ELSE,
        ELIF,
        SWITCH,
        CASE,
        MATCH,
        WITH,
        AS,
        DEFAULT,
        OP_ASSIGN,
        COLON,
        RANGE,
        COND_OR,
        COND_AND,
        OP_COMPARE,
        OR,
        XOR,
        AND,
        OP_SHIFT,
        OP_TERM,
        OP_FACTOR,
        POW,
        OP_UNARY,
        LEFT_PAR,
        RIGHT_PAR,
        LEFT_BRACKET,
        RIGHT_BRACKET,
        COMMA,
        DOT,
    };

// $insert STYPE
    typedef Meta__::SType STYPE__;


    private:
                        // state  semval
        typedef std::pair<size_t, STYPE__> StatePair;
                       // token   semval
        typedef std::pair<int,    STYPE__> TokenPair;

        int d_stackIdx = -1;
        std::vector<StatePair> d_stateStack;
        StatePair  *d_vsp = 0;       // points to the topmost value stack
        size_t      d_state = 0;

        TokenPair   d_next;
        int         d_token;

        bool        d_terminalToken = false;
        bool        d_recovery = false;


    protected:
        enum Return__
        {
            PARSE_ACCEPT__ = 0,   // values used as parse()'s return values
            PARSE_ABORT__  = 1
        };
        enum ErrorRecovery__
        {
            UNEXPECTED_TOKEN__,
        };

        bool        d_actionCases__ = false;    // set by options/directives
        bool        d_debug__ = true;
        size_t      d_requiredTokens__;
        size_t      d_nErrors__;                // initialized by clearin()
        size_t      d_acceptedTokens__;
        STYPE__     d_val__;


        ParserBase();

// $insert debugdecl
        static std::ostringstream s_out__;
        
        std::string symbol__(int value) const;
        std::string stype__(char const *pre, STYPE__ const &semVal,
                            char const *post = "") const;
        static std::ostream &dflush__(std::ostream &out);
        void ABORT() const;
        void ACCEPT() const;
        void ERROR() const;

        STYPE__ &vs__(int idx);             // value stack element idx 
        int  lookup__() const;
        int  savedToken__() const;
        int  token__() const;
        size_t stackSize__() const;
        size_t state__() const;
        size_t top__() const;
        void clearin__();
        void errorVerbose__();
        void lex__(int token);
        void popToken__();
        void pop__(size_t count = 1);
        void pushToken__(int token);
        void push__(size_t nextState);
        void redoToken__();
        bool recovery__() const;
        void reduce__(int rule);
        void shift__(int state);
        void startRecovery__();

    public:
        void setDebug(bool mode);
        void setDebug(DebugMode__ mode);
}; 

// hdr/abort
inline void ParserBase::ABORT() const
{
    throw PARSE_ABORT__;
}

// hdr/accept
inline void ParserBase::ACCEPT() const
{
    throw PARSE_ACCEPT__;
}


// hdr/error
inline void ParserBase::ERROR() const
{
    throw UNEXPECTED_TOKEN__;
}

// hdr/savedtoken
inline int ParserBase::savedToken__() const
{
    return d_next.first;
}

// hdr/opbitand
inline ParserBase::DebugMode__ operator&(ParserBase::DebugMode__ lhs,
                                     ParserBase::DebugMode__ rhs)
{
    return static_cast<ParserBase::DebugMode__>(
            static_cast<int>(lhs) & rhs);
}

// hdr/opbitor
inline ParserBase::DebugMode__ operator|(ParserBase::DebugMode__ lhs, 
                                     ParserBase::DebugMode__ rhs)
{
    return static_cast<ParserBase::DebugMode__>(static_cast<int>(lhs) | rhs);
};

// hdr/recovery
inline bool ParserBase::recovery__() const
{
    return d_recovery;
}

// hdr/stacksize
inline size_t ParserBase::stackSize__() const
{
    return d_stackIdx + 1;
}

// hdr/state
inline size_t ParserBase::state__() const
{
    return d_state;
}

// hdr/token
inline int ParserBase::token__() const
{
    return d_token;
}

// hdr/vs
inline ParserBase::STYPE__ &ParserBase::vs__(int idx) 
{
    return (d_vsp + idx)->second;
}

// hdr/tail
// For convenience, when including ParserBase.h its symbols are available as
// symbols in the class Parser, too.
#define Parser ParserBase


#endif



