// Generated by Flexc++ V2.06.02 on Wed, 13 Nov 2019 10:25:59 +0300

#ifndef Scanner_H_INCLUDED_
#define Scanner_H_INCLUDED_

// $insert baseclass_h
#include "Scannerbase.h"
#include <map>
#include <functional>
#include "const.h"

// $insert classHead
class Scanner: public ScannerBase
{
    public:
        bool preprocessor = false;

        explicit Scanner(std::istream &in = std::cin,
                                std::ostream &out = std::cout);

        Scanner(std::string const &infile, std::string const &outfile);
        
        // $insert lexFunctionDecl
        int lex();
        typedef std::function<void(unsigned, const std::string&)> onNextLine_t;
        void setSval(Parser::STYPE__* d_val__, std::map<std::string, Const> *consts, onNextLine_t onNextLine);
        void setSourceForGetLine(const std::string& getLineSource);
        void setFilename(std::string const &name) { ScannerBase::setFilename(name); }

    private:
        int lex__();
        int executeAction__(size_t ruleNr);

        void print();
        void preCode();     // re-implement this function for code that must 
                            // be exec'ed before the patternmatching starts

        void postCode(PostEnum__ type);    
                            // re-implement this function for code that must 
                            // be exec'ed after the rules's actions.

        std::string getLine(unsigned l);

        Parser::STYPE__* d_val = nullptr;
        std::map<std::string, Const>* consts = nullptr;
        onNextLine_t onNextLine;
        std::string getLineSource;
        unsigned getLineCacheLine = 1;
        std::string::size_type getLineCacheOff = 0;
};

// $insert scannerConstructors
inline Scanner::Scanner(std::istream &in, std::ostream &out)
:
    ScannerBase(in, out)
{}

inline Scanner::Scanner(std::string const &infile, std::string const &outfile)
:
    ScannerBase(infile, outfile)
{}

// $insert inlineLexFunction
inline int Scanner::lex()
{
    return lex__();
}

inline void Scanner::preCode() 
{
    // optionally replace by your own code
}

inline void Scanner::postCode(PostEnum__ type) 
{
    // optionally replace by your own code
}

inline void Scanner::print() 
{    
    print__();
}

inline void Scanner::setSval(Parser::STYPE__* d_val__,  std::map<std::string, Const>* _consts, onNextLine_t _onNextLine)
{
    onNextLine = _onNextLine;
    consts = _consts;
    d_val = d_val__;
}

inline void Scanner::setSourceForGetLine(const std::string& _getLineSource)
{
    getLineSource = _getLineSource;
    getLineCacheLine = 1;
    getLineCacheOff = 0;
}

inline std::string Scanner::getLine(unsigned line)
{
    std::string::size_type pos = 0;
    unsigned currentLine = 1;
    if (line >= getLineCacheLine)
    {
        currentLine = getLineCacheLine;
        pos = getLineCacheOff;
    }
    for(; currentLine < line; currentLine++)
    {
        pos = getLineSource.find('\n', pos);
        if (pos == getLineSource.npos) return "";
        pos++;
    }
    getLineCacheLine = line;
    getLineCacheOff = pos;

    while (getLineSource.data()[pos] == ' ') pos++;
    std::string::size_type pos1 = getLineSource.find('\n', pos);
    return pos1 == getLineSource.npos ? getLineSource.substr(pos) : getLineSource.substr(pos, pos1 - pos);
}

#endif // Scanner_H_INCLUDED_

